<?php

namespace WCW\CoavBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightRepository extends EntityRepository
{
}
