reservation_index:
    path:     /
    defaults: { _controller: "WCWCoavBundle:Reservation:index" }
    methods:  GET

reservation_show:
    path:     /{id}/show
    defaults: { _controller: "WCWCoavBundle:Reservation:show" }
    methods:  GET



