WCW\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCW\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        departure:
            type: string
            length: '4'
        arrival:
            type: string
            length: '4'
        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
            nullable: true
        takeofTime:
            type: datetime
    lifecycleCallbacks: {  }
