WCW\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCW\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
            nullable: true
        takeofTime:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCW\CoavBundle\Entity\Terrain
            inversedBy: departures
        arrival:
            targetEntity: WCW\CoavBundle\Entity\Terrain
            inversedBy: arrivals
        plane:
            targetEntity: WCW\CoavBundle\Entity\PlanelModel
            inversedBy: planes
    oneToMany:
        reservations:
            targetEntity: WCW\CoavBundle\Entity\Reservation
            mappedBy: reservation
