WCW\CoavBundle\Entity\Terrain:
    type: entity
    table: null
    repositoryClass: WCW\CoavBundle\Repository\TerrainRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        icao:
            type: string
            length: '4'
        latitude:
            type: float
        longitude:
            type: float
        city:
            type: string
            length: 255
        country:
            type: string
            length: 255
    lifecycleCallbacks: {  }
